name: Release & pre-release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest

    services:
        covid-drdb-devdb:
          image: postgres:latest
          env:
            POSTGRES_HOST_AUTH_METHOD: trust
          ports:
            - 5432:5432
          options: >-
            --health-cmd pg_isready
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5

    steps:
      - name: Checkout payload repository
        uses: actions/checkout@v3
        with:
          path: covid-drdb-payload

      - name: Checkout covid-drdb repository
        uses: actions/checkout@v3
        with:
          repository: hivdb/covid-drdb
          path: covid-drdb

      - name: Integration
        env:
          POSTGRES_PORT: 5432
          POSTGRES_HOST: localhost
        run: |
          set -e
          cd covid-drdb
          docker pull hivdb/covid-drdb-builder:latest
          mkdir -p local/sqls
          docker run --rm -v="$(pwd)":/covid-drdb/ -v="$(dirname $(pwd))"/covid-drdb-payload:/covid-drdb/payload hivdb/covid-drdb-builder:latest scripts/export-sqls.sh
          psql -v ON_ERROR_STOP=1 -U postgres -h localhost -f local/sqls/01_schema.sql
          psql -v ON_ERROR_STOP=1 -U postgres -h localhost -f local/sqls/02_data_tables.sql
          psql -v ON_ERROR_STOP=1 -U postgres -h localhost -f local/sqls/03_derived_tables.sql

      - name: Publish release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          docker run --rm -v="$(pwd)":/covid-drdb/ -v="$(dirname $(pwd))"/covid-drdb-payload:/covid-drdb/payload -e GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} --network=${{ job.container.network }} hivdb/covid-drdb-builder:latest scripts/github-release.sh ${{ github.ref_name }}
